[package]
name = "shining-emulator-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = { version = "0.19.0-rc.1", default-features = false, features = [
    "bevy_asset",
    "bevy_core_pipeline",
    "bevy_render",
    "bevy_scene",
    "bevy_sprite",
    "bevy_state",
    "bevy_text",
    "bevy_ui",
    "bevy_ui_render",
    "bevy_winit",
    "png",
    "x11",
] }
fastrand = "2.4.1"
