pub use crate::dimensions::{
    BINARY_TEXT_CELL_HEIGHT, BINARY_TEXT_CELL_WIDTH, BINARY_TEXT_FONT_SIZE, BINARY_TEXT_INSET,
};

pub const BINARY_TEXT_MAX_OPACITY: f32 = 0.30;
pub const BINARY_TEXT_DIGIT_POOL_SIZE: usize = 256;
pub const BINARY_TEXT_FADE_SECONDS: f32 = 0.22;
pub const BINARY_TEXT_GROUP_MIN_DIGITS: usize = 7;
pub const BINARY_TEXT_GROUP_MAX_DIGITS: usize = 18;
pub const BINARY_TEXT_GROUP_SPAWN_MIN_SECONDS: f32 = 0.08;
pub const BINARY_TEXT_GROUP_SPAWN_MAX_SECONDS: f32 = 0.28;
pub const BINARY_TEXT_WAVE_SECONDS_PER_DIGIT: f32 = 0.035;
pub const BINARY_TEXT_INFLUENCE_DIGITS: f32 = 4.2;
pub const BINARY_TEXT_Z: f32 = -70.0;
