[package]
name = "app"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = { workspace = true }
bevy-midi-graph = { git = "https://github.com/shining-grimace/bevy-midi-graph.git", rev = "dac4910acf5ad3ef8343f598d449789003105d50" }
directories = "6.0.0"
fastrand = "2.4.1"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
jsonpath_lib = "0.3.0"
ureq = { version = "3", default-features = false, features = ["rustls"] }
sha1 = "0.11.0"
hex = "0.4.3"
uuid = { version = "1.23.1", features = ["v4", "serde"] }
libc = "0.2"

[target.'cfg(all(unix, not(any(target_os = "macos", target_os = "android", target_os = "emscripten"))))'.dependencies]
arboard = { version = "3.6.1", default-features = false, features = ["wayland-data-control"] }
