pub use crate::dimensions::{
    BACKGROUND_GAMEBOY_HEIGHT, BACKGROUND_GAMEBOY_WIDTH, BACKGROUND_WINDOW_MARGIN,
    OFFSCREEN_MARGIN, PARTICLE_MAX_SIZE, PARTICLE_MIN_SIZE,
};

pub const BACKGROUND_MAX_OPACITY: f32 = 0.15;
pub const BACKGROUND_FADE_SECONDS: f32 = 0.45;
pub const BACKGROUND_Z: f32 = -100.0;
pub const PARTICLE_Z: f32 = -60.0;
pub const PARTICLE_COUNT: usize = 64;
pub const PARTICLE_MIN_MAX_SPEED: f32 = 12.0;
pub const PARTICLE_MAX_MAX_SPEED: f32 = 42.0;
pub const PARTICLE_MIN_DRIFT_SECONDS: f32 = 2.2;
pub const PARTICLE_MAX_DRIFT_SECONDS: f32 = 6.5;
pub const PARTICLE_BASE_ALPHA_MIN: f32 = 0.10;
pub const PARTICLE_BASE_ALPHA_MAX: f32 = 0.34;
pub const PARTICLE_PULSE_SPEED_MIN: f32 = 0.8;
pub const PARTICLE_PULSE_SPEED_MAX: f32 = 1.9;
pub const BLINK_MIN_DELAY_SECONDS: f32 = 0.35;
pub const BLINK_MAX_DELAY_SECONDS: f32 = 2.4;
pub const BLINK_MIN_DURATION_SECONDS: f32 = 0.05;
pub const BLINK_MAX_DURATION_SECONDS: f32 = 0.5;
