pub const BACKGROUND_GAMEBOY_WIDTH: f32 = 160.0;
pub const BACKGROUND_GAMEBOY_HEIGHT: f32 = 144.0;
pub const BACKGROUND_WINDOW_MARGIN: f32 = 48.0;
pub const PARTICLE_MIN_SIZE: f32 = 2.0;
pub const PARTICLE_MAX_SIZE: f32 = 7.0;
pub const OFFSCREEN_MARGIN: f32 = 24.0;

pub const GAME_BOY_SCREEN_WIDTH: usize = 160;
pub const GAME_BOY_SCREEN_HEIGHT: usize = 144;
pub const GAME_BOY_SCREEN_WIDTH_U32: u32 = 160;
pub const GAME_BOY_SCREEN_HEIGHT_U32: u32 = 144;
pub const SGB_SCREEN_WIDTH: usize = 256;
pub const SGB_SCREEN_HEIGHT: usize = 224;
pub const SGB_SCREEN_WIDTH_U32: u32 = 256;
pub const SGB_SCREEN_HEIGHT_U32: u32 = 224;
pub const SGB_GAME_BOY_X_OFFSET: usize = (SGB_SCREEN_WIDTH - GAME_BOY_SCREEN_WIDTH) / 2;
pub const SGB_GAME_BOY_Y_OFFSET: usize = (SGB_SCREEN_HEIGHT - GAME_BOY_SCREEN_HEIGHT) / 2;
pub const GAME_BOY_RGB_CHANNELS: usize = 3;
pub const GAME_BOY_RGBA_CHANNELS: usize = 4;
pub const GAME_BOY_FRAME_BUFFER_BYTES: usize =
    GAME_BOY_SCREEN_WIDTH * GAME_BOY_SCREEN_HEIGHT * GAME_BOY_RGB_CHANNELS;
pub const GAME_BOY_TEXTURE_BYTES: usize =
    GAME_BOY_SCREEN_WIDTH * GAME_BOY_SCREEN_HEIGHT * GAME_BOY_RGBA_CHANNELS;
pub const SGB_TEXTURE_BYTES: usize = SGB_SCREEN_WIDTH * SGB_SCREEN_HEIGHT * GAME_BOY_RGBA_CHANNELS;

pub const BINARY_TEXT_FONT_SIZE: f32 = 18.0;
pub const BINARY_TEXT_CELL_WIDTH: f32 = 18.0;
pub const BINARY_TEXT_CELL_HEIGHT: f32 = 22.0;
pub const BINARY_TEXT_INSET: f32 = 28.0;

pub const CIRCUIT_WINDOW_MARGIN: f32 = BACKGROUND_WINDOW_MARGIN * 0.5;
pub const CIRCUIT_MIN_WINDOW_MARGIN: f32 = 22.0;
pub const CIRCUIT_NODE_WIDTH: f32 = 92.0;
pub const CIRCUIT_NODE_HEIGHT: f32 = 76.0;
pub const CIRCUIT_NODE_MIN_SCALE: f32 = 0.62;
pub const CIRCUIT_TRACE_THICKNESS: f32 = 2.4;
pub const CIRCUIT_NODE_THICKNESS: f32 = 2.6;
pub const CIRCUIT_ELEMENT_SIZE: f32 = 46.0;
pub const CIRCUIT_LAYOUT_WIDTH: f32 = 1040.0;
pub const CIRCUIT_LAYOUT_HEIGHT: f32 = 560.0;

pub const UI_CORNER_RADIUS: f32 = 8.0;
pub const UI_BORDER_WIDTH: f32 = 2.0;
pub const UI_ELEMENT_HEIGHT: f32 = 48.0;
pub const UI_LIST_ROW_HEIGHT: f32 = UI_ELEMENT_HEIGHT;
pub const UI_BUTTON_WIDTH: f32 = 208.0;
pub const UI_MULTI_SELECT_WIDTH: f32 = 260.0;
pub const UI_FILE_PICKER_WIDTH: f32 = 480.0;
pub const UI_LIST_HEIGHT: f32 = 248.0;
pub const UI_SCROLLBAR_WIDTH: f32 = 10.0;
pub const UI_INNER_PADDING: f32 = 14.0;
pub const UI_PANEL_GAP: f32 = 18.0;
pub const UI_CONTENT_GAP: f32 = 24.0;
pub const UI_CONTROL_GAP: f32 = 20.0;
pub const UI_FIELD_GAP: f32 = 12.0;
pub const UI_SECTION_GAP: f32 = 28.0;
pub const UI_BUTTON_ROW_GAP: f32 = 16.0;
pub const UI_SCREEN_PADDING: f32 = 52.0;
pub const UI_PORTRAIT_SCREEN_PADDING: f32 = 32.0;
pub const UI_WIDE_CONTENT_WIDTH: f32 = 1680.0;
pub const UI_HEADING_FONT_SIZE: f32 = 32.0;
pub const UI_BODY_FONT_SIZE: f32 = 20.0;
pub const UI_CONTROL_FONT_SIZE: f32 = 22.0;
pub const UI_HINT_MARGIN: f32 = 40.0;

pub const ACTION_HINT_ICON_SIZE: f32 = 48.0;
pub const ACTION_HINT_GAP: f32 = 42.0;
pub const GAMEPLAY_ERROR_ICON_SIZE: f32 = 72.0;
pub const TOUCH_OVERLAY_MARGIN: f32 = 18.0;
pub const TOUCH_OVERLAY_DPAD_CLUSTER_SIZE: f32 = 128.0;
pub const TOUCH_OVERLAY_DPAD_CLUSTER_HEIGHT: f32 = 174.0;
pub const TOUCH_OVERLAY_DPAD_ICON_LONG: f32 = 64.0;
pub const TOUCH_OVERLAY_DPAD_ICON_SHORT: f32 = 32.0;
pub const TOUCH_OVERLAY_FACE_BUTTON_SIZE: f32 = 87.0;
pub const TOUCH_OVERLAY_FACE_BUTTON_GAP: f32 = 16.0;
pub const TOUCH_OVERLAY_FACE_ICON_SIZE: f32 = 66.0;
pub const TOUCH_OVERLAY_SYSTEM_BUTTON_WIDTH: f32 = 78.0;
pub const TOUCH_OVERLAY_SYSTEM_BUTTON_HEIGHT: f32 = 34.0;
pub const TOUCH_OVERLAY_SYSTEM_BUTTON_GAP: f32 = 12.0;
pub const TOUCH_OVERLAY_SYSTEM_ICON_WIDTH: f32 = 66.0;
pub const TOUCH_OVERLAY_SYSTEM_ICON_HEIGHT: f32 = 33.0;
pub const TOUCH_OVERLAY_SYSTEM_ROW_GAP: f32 = 10.0;
pub const LOADING_INDICATOR_SQUARE_SIZE: f32 = 24.0;
pub const LOADING_INDICATOR_GRID_SIZE: f32 = LOADING_INDICATOR_SQUARE_SIZE * 2.0;
pub const FILE_PICKER_GAP: f32 = 12.0;
pub const POPUP_OPTION_GAP: f32 = 8.0;
pub const POPUP_SCROLLBAR_GAP: f32 = 10.0;
pub const POPUP_SCROLLBAR_THUMB_HEIGHT: f32 = 56.0;
pub const POPUP_TOP_OFFSET: f32 = UI_ELEMENT_HEIGHT + POPUP_OPTION_GAP;
pub const BACK_BUTTON_SIZE: f32 = UI_ELEMENT_HEIGHT * 1.5;
pub const BACK_ICON_SIZE_PX: f32 = 34.0 * 1.5;
pub const WHEEL_SCROLL_PIXELS: f32 = 48.0;
pub const KEY_SCROLL_PIXELS: f32 = 48.0;
pub const SCROLLBAR_TRACK_PADDING: f32 = 6.0;
pub const SCROLLBAR_VERTICAL_PADDING: f32 = 12.0;

pub const HERO_TEXTURE_SIZE: f32 = 454.0;
pub const HERO_GRID_UNITS: f32 = 2.0;
pub const HERO_IMAGE_SIZE: f32 = 184.0;

pub const UI_SIDEBAR_WIDTH: f32 = 280.0;
pub const UI_SIDEBAR_TOP_GAP: f32 = 50.0;
pub const UI_SIDEBAR_GROUP_GAP: f32 = 46.0;
pub const UI_SCROLL_CONTENT_BOTTOM_PADDING: f32 = 320.0;

pub const UI_PRIMARY_COLUMN_PERCENT: f32 = 48.0;
pub const UI_SECONDARY_COLUMN_PERCENT: f32 = 52.0;
pub const UI_WIDE_PRIMARY_COLUMN_PERCENT: f32 = 58.0;
pub const UI_WIDE_SECONDARY_COLUMN_PERCENT: f32 = 42.0;
pub const UI_FORM_LEFT_COLUMN_FLEX: f32 = 38.0;
pub const UI_FORM_RIGHT_COLUMN_FLEX: f32 = 62.0;
pub const UI_MAPPING_LEFT_COLUMN_PERCENT: f32 = 40.0;
pub const UI_MAPPING_CENTRE_COLUMN_PERCENT: f32 = 28.0;
pub const UI_MAPPING_RIGHT_COLUMN_PERCENT: f32 = 32.0;
pub const UI_MAPPING_GAMEBOY_COLUMNS_PERCENT: f32 =
    UI_MAPPING_LEFT_COLUMN_PERCENT + UI_MAPPING_CENTRE_COLUMN_PERCENT;
pub const UI_MAPPING_GAMEBOY_LEFT_COLUMN_PERCENT: f32 =
    UI_MAPPING_LEFT_COLUMN_PERCENT / UI_MAPPING_GAMEBOY_COLUMNS_PERCENT * 100.0;
pub const UI_MAPPING_GAMEBOY_CENTRE_COLUMN_PERCENT: f32 =
    UI_MAPPING_CENTRE_COLUMN_PERCENT / UI_MAPPING_GAMEBOY_COLUMNS_PERCENT * 100.0;
pub const UI_MAPPING_FORM_BOTTOM_PADDING: f32 = 72.0;

pub const APP_LOGO_WIDTH: f32 = 520.0;
pub const DEVELOPER_LOGO_SIZE: f32 = 72.0;
pub const DEVELOPER_BRANDING_MARGIN: f32 = 32.0;
pub const DEVELOPER_BRANDING_GAP: f32 = 16.0;
pub const DEVELOPER_TEXT_SIZE: f32 = 28.0;
