use bevy::input::gamepad::GamepadButton;
use bevy::input::keyboard::KeyCode;

use crate::storage::input_mappings::InputKeyId;

pub(crate) fn key_code_from_id(key_id: InputKeyId) -> Option<KeyCode> {
    match key_id {
        InputKeyId::ArrowLeft => Some(KeyCode::ArrowLeft),
        InputKeyId::ArrowRight => Some(KeyCode::ArrowRight),
        InputKeyId::ArrowUp => Some(KeyCode::ArrowUp),
        InputKeyId::ArrowDown => Some(KeyCode::ArrowDown),
        InputKeyId::KeyA => Some(KeyCode::KeyA),
        InputKeyId::KeyB => Some(KeyCode::KeyB),
        InputKeyId::KeyC => Some(KeyCode::KeyC),
        InputKeyId::KeyD => Some(KeyCode::KeyD),
        InputKeyId::KeyE => Some(KeyCode::KeyE),
        InputKeyId::KeyF => Some(KeyCode::KeyF),
        InputKeyId::KeyG => Some(KeyCode::KeyG),
        InputKeyId::KeyH => Some(KeyCode::KeyH),
        InputKeyId::KeyI => Some(KeyCode::KeyI),
        InputKeyId::KeyJ => Some(KeyCode::KeyJ),
        InputKeyId::KeyK => Some(KeyCode::KeyK),
        InputKeyId::KeyL => Some(KeyCode::KeyL),
        InputKeyId::KeyM => Some(KeyCode::KeyM),
        InputKeyId::KeyN => Some(KeyCode::KeyN),
        InputKeyId::KeyO => Some(KeyCode::KeyO),
        InputKeyId::KeyP => Some(KeyCode::KeyP),
        InputKeyId::KeyQ => Some(KeyCode::KeyQ),
        InputKeyId::KeyR => Some(KeyCode::KeyR),
        InputKeyId::KeyS => Some(KeyCode::KeyS),
        InputKeyId::KeyT => Some(KeyCode::KeyT),
        InputKeyId::KeyU => Some(KeyCode::KeyU),
        InputKeyId::KeyV => Some(KeyCode::KeyV),
        InputKeyId::KeyW => Some(KeyCode::KeyW),
        InputKeyId::KeyZ => Some(KeyCode::KeyZ),
        InputKeyId::KeyX => Some(KeyCode::KeyX),
        InputKeyId::KeyY => Some(KeyCode::KeyY),
        InputKeyId::Enter => Some(KeyCode::Enter),
        InputKeyId::ShiftRight => Some(KeyCode::ShiftRight),
        InputKeyId::ShiftLeft => Some(KeyCode::ShiftLeft),
        InputKeyId::Escape => Some(KeyCode::Escape),
        InputKeyId::ControlLeft => Some(KeyCode::ControlLeft),
        InputKeyId::ControlRight => Some(KeyCode::ControlRight),
        InputKeyId::Space => Some(KeyCode::Space),
        InputKeyId::Tab => Some(KeyCode::Tab),
        InputKeyId::Backspace => Some(KeyCode::Backspace),
        InputKeyId::Digit0 => Some(KeyCode::Digit0),
        InputKeyId::Digit1 => Some(KeyCode::Digit1),
        InputKeyId::Digit2 => Some(KeyCode::Digit2),
        InputKeyId::Digit3 => Some(KeyCode::Digit3),
        InputKeyId::Digit4 => Some(KeyCode::Digit4),
        InputKeyId::Digit5 => Some(KeyCode::Digit5),
        InputKeyId::Digit6 => Some(KeyCode::Digit6),
        InputKeyId::Digit7 => Some(KeyCode::Digit7),
        InputKeyId::Digit8 => Some(KeyCode::Digit8),
        InputKeyId::Digit9 => Some(KeyCode::Digit9),
        _ => None,
    }
}

pub(crate) fn key_code_id(key_code: KeyCode) -> Option<InputKeyId> {
    match key_code {
        KeyCode::ArrowLeft => Some(InputKeyId::ArrowLeft),
        KeyCode::ArrowRight => Some(InputKeyId::ArrowRight),
        KeyCode::ArrowUp => Some(InputKeyId::ArrowUp),
        KeyCode::ArrowDown => Some(InputKeyId::ArrowDown),
        KeyCode::KeyA => Some(InputKeyId::KeyA),
        KeyCode::KeyB => Some(InputKeyId::KeyB),
        KeyCode::KeyC => Some(InputKeyId::KeyC),
        KeyCode::KeyD => Some(InputKeyId::KeyD),
        KeyCode::KeyE => Some(InputKeyId::KeyE),
        KeyCode::KeyF => Some(InputKeyId::KeyF),
        KeyCode::KeyG => Some(InputKeyId::KeyG),
        KeyCode::KeyH => Some(InputKeyId::KeyH),
        KeyCode::KeyI => Some(InputKeyId::KeyI),
        KeyCode::KeyJ => Some(InputKeyId::KeyJ),
        KeyCode::KeyK => Some(InputKeyId::KeyK),
        KeyCode::KeyL => Some(InputKeyId::KeyL),
        KeyCode::KeyM => Some(InputKeyId::KeyM),
        KeyCode::KeyN => Some(InputKeyId::KeyN),
        KeyCode::KeyO => Some(InputKeyId::KeyO),
        KeyCode::KeyP => Some(InputKeyId::KeyP),
        KeyCode::KeyQ => Some(InputKeyId::KeyQ),
        KeyCode::KeyR => Some(InputKeyId::KeyR),
        KeyCode::KeyS => Some(InputKeyId::KeyS),
        KeyCode::KeyT => Some(InputKeyId::KeyT),
        KeyCode::KeyU => Some(InputKeyId::KeyU),
        KeyCode::KeyV => Some(InputKeyId::KeyV),
        KeyCode::KeyW => Some(InputKeyId::KeyW),
        KeyCode::KeyZ => Some(InputKeyId::KeyZ),
        KeyCode::KeyX => Some(InputKeyId::KeyX),
        KeyCode::KeyY => Some(InputKeyId::KeyY),
        KeyCode::Enter => Some(InputKeyId::Enter),
        KeyCode::ShiftRight => Some(InputKeyId::ShiftRight),
        KeyCode::ShiftLeft => Some(InputKeyId::ShiftLeft),
        KeyCode::Escape => Some(InputKeyId::Escape),
        KeyCode::ControlLeft => Some(InputKeyId::ControlLeft),
        KeyCode::ControlRight => Some(InputKeyId::ControlRight),
        KeyCode::Space => Some(InputKeyId::Space),
        KeyCode::Tab => Some(InputKeyId::Tab),
        KeyCode::Backspace => Some(InputKeyId::Backspace),
        KeyCode::Digit0 => Some(InputKeyId::Digit0),
        KeyCode::Digit1 => Some(InputKeyId::Digit1),
        KeyCode::Digit2 => Some(InputKeyId::Digit2),
        KeyCode::Digit3 => Some(InputKeyId::Digit3),
        KeyCode::Digit4 => Some(InputKeyId::Digit4),
        KeyCode::Digit5 => Some(InputKeyId::Digit5),
        KeyCode::Digit6 => Some(InputKeyId::Digit6),
        KeyCode::Digit7 => Some(InputKeyId::Digit7),
        KeyCode::Digit8 => Some(InputKeyId::Digit8),
        KeyCode::Digit9 => Some(InputKeyId::Digit9),
        _ => None,
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn all_letter_key_codes_have_input_ids() {
        for key_code in [
            KeyCode::KeyA,
            KeyCode::KeyB,
            KeyCode::KeyC,
            KeyCode::KeyD,
            KeyCode::KeyE,
            KeyCode::KeyF,
            KeyCode::KeyG,
            KeyCode::KeyH,
            KeyCode::KeyI,
            KeyCode::KeyJ,
            KeyCode::KeyK,
            KeyCode::KeyL,
            KeyCode::KeyM,
            KeyCode::KeyN,
            KeyCode::KeyO,
            KeyCode::KeyP,
            KeyCode::KeyQ,
            KeyCode::KeyR,
            KeyCode::KeyS,
            KeyCode::KeyT,
            KeyCode::KeyU,
            KeyCode::KeyV,
            KeyCode::KeyW,
            KeyCode::KeyX,
            KeyCode::KeyY,
            KeyCode::KeyZ,
        ] {
            let key_id = key_code_id(key_code).expect("letter key code should map to input id");
            assert_eq!(key_code_from_id(key_id), Some(key_code));
        }
    }
}

pub(crate) fn gamepad_button_from_id(key_id: InputKeyId) -> Option<GamepadButton> {
    match key_id {
        InputKeyId::South => Some(GamepadButton::South),
        InputKeyId::East => Some(GamepadButton::East),
        InputKeyId::North => Some(GamepadButton::North),
        InputKeyId::West => Some(GamepadButton::West),
        InputKeyId::C => Some(GamepadButton::C),
        InputKeyId::Z => Some(GamepadButton::Z),
        InputKeyId::LeftTrigger => Some(GamepadButton::LeftTrigger),
        InputKeyId::LeftTrigger2 => Some(GamepadButton::LeftTrigger2),
        InputKeyId::RightTrigger => Some(GamepadButton::RightTrigger),
        InputKeyId::RightTrigger2 => Some(GamepadButton::RightTrigger2),
        InputKeyId::Select => Some(GamepadButton::Select),
        InputKeyId::Start => Some(GamepadButton::Start),
        InputKeyId::Mode => Some(GamepadButton::Mode),
        InputKeyId::LeftThumb => Some(GamepadButton::LeftThumb),
        InputKeyId::RightThumb => Some(GamepadButton::RightThumb),
        InputKeyId::DPadUp => Some(GamepadButton::DPadUp),
        InputKeyId::DPadDown => Some(GamepadButton::DPadDown),
        InputKeyId::DPadLeft => Some(GamepadButton::DPadLeft),
        InputKeyId::DPadRight => Some(GamepadButton::DPadRight),
        _ => None,
    }
}

pub(crate) fn gamepad_button_id(button: GamepadButton) -> Option<InputKeyId> {
    match button {
        GamepadButton::South => Some(InputKeyId::South),
        GamepadButton::East => Some(InputKeyId::East),
        GamepadButton::North => Some(InputKeyId::North),
        GamepadButton::West => Some(InputKeyId::West),
        GamepadButton::C => Some(InputKeyId::C),
        GamepadButton::Z => Some(InputKeyId::Z),
        GamepadButton::LeftTrigger => Some(InputKeyId::LeftTrigger),
        GamepadButton::LeftTrigger2 => Some(InputKeyId::LeftTrigger2),
        GamepadButton::RightTrigger => Some(InputKeyId::RightTrigger),
        GamepadButton::RightTrigger2 => Some(InputKeyId::RightTrigger2),
        GamepadButton::Select => Some(InputKeyId::Select),
        GamepadButton::Start => Some(InputKeyId::Start),
        GamepadButton::Mode => Some(InputKeyId::Mode),
        GamepadButton::LeftThumb => Some(InputKeyId::LeftThumb),
        GamepadButton::RightThumb => Some(InputKeyId::RightThumb),
        GamepadButton::DPadUp => Some(InputKeyId::DPadUp),
        GamepadButton::DPadDown => Some(InputKeyId::DPadDown),
        GamepadButton::DPadLeft => Some(InputKeyId::DPadLeft),
        GamepadButton::DPadRight => Some(InputKeyId::DPadRight),
        GamepadButton::Other(_) => None,
    }
}
