pub use crate::dimensions::{
    CIRCUIT_ELEMENT_SIZE, CIRCUIT_LAYOUT_HEIGHT, CIRCUIT_LAYOUT_WIDTH, CIRCUIT_MIN_WINDOW_MARGIN,
    CIRCUIT_NODE_HEIGHT, CIRCUIT_NODE_MIN_SCALE, CIRCUIT_NODE_THICKNESS, CIRCUIT_NODE_WIDTH,
    CIRCUIT_TRACE_THICKNESS, CIRCUIT_WINDOW_MARGIN,
};

pub const CIRCUIT_MAX_OPACITY: f32 = 0.48;
pub const CIRCUIT_FADE_SECONDS: f32 = 0.45;
pub const CIRCUIT_ROUNDING_SEGMENTS: usize = 5;
pub const CIRCUIT_Z: f32 = -80.0;
pub const CIRCUIT_NODE_Z: f32 = -78.0;
pub const CIRCUIT_ELEMENT_Z: f32 = -76.0;
